### ISSUE TITLE
[1.12.2] Game Crash on World Load

### ISSUE THREAD

**Issue by PhoxLogic** [Azanor/thaumcraft-api#16]
While working on my personal 1.12 modpack I found a rather annoying crash. While the game starts up & loads just fine, as soon as you load a world, the game crashes. Sometimes it's instant, sometimes you can actually roam around the world for a while, but either way: The game crashes very shortly after a world loads. At first I thought this was a Simply Jetpacks 2 issue, since I was seeing error messages in the log regarding it. However, after taking a closer look at it I noticed that the main crash pointed to Thaumcraft. I've no clue whether this is just an incompatibility with another mod or not, but either way I figured it was best to bring up here. If you wish to see the log in more detail, it can be found here: [https://paste.ee/p/pcbeV]

**Comment by gw2princeps** [comment]
I can confirm this! Exactly the same [stacktrace](https://gist.github.com/SpatiumPrinceps/79ca9638ce6906df8b78a7ff52f9433c).

**Comment by catchra** [comment]
mine is on a server version 1.12.2 the crash stops as soon as i remove `Thaumcraft-1.12.2-6.1.BETA15.jar`

[crash-2018-06-02_14.02.38-server.txt](https://github.com/Azanor/thaumcraft-api/files/2065241/crash-2018-06-02_14.02.38-server.txt)
[debug.log](https://github.com/Azanor/thaumcraft-api/files/2065243/debug.log)

**Comment by tamanor** [comment]
Hi I am getting the same crash error cannot upload log atm but i will tomorrow since its on my server computer.
But the crash the people above have posted is same as what I am getting. I am using BiomesOPlenty and Simple Dimensions on my server along with a bunch of others. 
But anyways I made a  new dimension using the Simple Dimensions since my main worlds uses different Terrain generator and it seems to not generate the Thaumcraft Magical Forest biome. So i used the Simple Dimensions mod to make a BiomesOPlenty world where i knew the Thaumcraft biomes would generate. It was all working fine until i came across the Magical Forest biome and as soon at the chunk is fully loaded the server crashes and gives the same error as the above people.
Seem to be with the EntityPech which is causing it.

this is on both 

Thaumcraft-1.12.2-6.1.BETA16.jar and Thaumcraft-1.12.2-6.1.BETA17.jar I have tested it on

But i can live without the Magical Forest for awhile ^^ just glad the mod is updated to 1.12
