### ISSUE TITLE
operandstack overflow error crash on server side.

### ISSUE THREAD

**Issue by Too-DAMN-Much** [Azanor/thaumcraft-api#49]
https://paste.ubuntu.com/p/5sxhQ86KTc/

please help track down who this belongs to.

**Comment by Azanor** [comment]
This does not seem to be TC related.

**Comment by wamc2017** [comment]
Like Azanor said, doesn't look like it's related to TC. Forge made some changes to chunk loading int 2761 according to the [changelog](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2768/forge-1.12.2-14.23.5.2768-changelog.txt), so give 2760 a try...

**Comment by Too-DAMN-Much** [comment]
okay thanks, it's not like there is any way i would know that other than asking people at random and eventually getting lucky like i'm doing, this is the least helpful error message ever.

**Comment by Too-DAMN-Much** [comment]
@wamc2017 i can't find a way to get that forge version, the earliest i have is 2765 i can't find a way to force install a specific version to mineos.

**Comment by wamc2017** [comment]
This is an issue tracker for the Thaumcrafts Api, not for any issue with any modpack/other mods/forge.
If you want help with those (and you don't know which mod is causing it), you should use the [minecraftforums](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods), the [forge forums](http://www.minecraftforge.net/forum/), [feed the beasts crashes reddit](https://www.reddit.com/r/FeedTheBeastCrashes/) (where you can post any mods issues) or [modded mc discord](http://discord.gg/moddedmc).

I haven't used mineos myself, but it seems they got their [own issue tracker](https://discourse.codeemo.com). You can get all forge versions on their [official site](https://files.minecraftforge.net). (Don't ask me how to use another version with mineos, because like I said, I never used it...)

**Comment by Too-DAMN-Much** [comment]
The only thing I give any fucks at all about is getting my server functional again for once. Anyone else can go fuck yourself with additional concerns

**Comment by wamc2017** [comment]
I wish you good luck in life with that attitude...

**Comment by Too-DAMN-Much** [comment]
You're quite ignorant, I get your point.
Why the duck would i need luck? I'm not some idiot gambler and I'm not the one who fucked up while making a mod and causing this crash, enjoy the 4 day from lex whoever is responsible he doesn't appear to take this particular crash lightly from what I've seen googling.
